### ISSUE TITLE
Packing Control byte with there command or data before calling I2C HAL write method

### ISSUE THREAD

**Issue by umanayana** [olikraus/u8g2#633] opened 2018-06-07 21:26 UTC
Hi, 

I am working on a project which uses the SSD1306. I came across your library and wanted to take it for a spin. I've come across a problem that is probably very specific to my implementation but I think on a whole it would be beneficial to add this in.

**Problem** 
When ever sending data or command the SSD1306 requires a control byte to be sent first 0x00 or 0x40. If this byte is sent individually on a system where many things use the same i2c line then the SSD1306 will almost always send a NACK when sending control byte as a single HAL call and then sending the command or data bytes. 

In my test I have found that if the delay between a control byte and the command or data is longer than 2 clock periods the SSD1306 send a NACK. I have not tried dropping the bus clock to see how this affect anything.

**Additional Notes:**
- Preemptive RTOS environment 
- Display is the lowest priority task
- Quite a few tasks are running in the system.
- I2C bus running at 400KHz

**Comment by olikraus** [comment] 2018-06-08 08:56
Did you observer a malfunction with u8g2 itself? 
Because, I actually would claim, that u8g2 will work correctly. 

Well all in all this is HAL issue and u8g2 itself does not implement HAL. However there is the HIL implementation for Arduino which also includes a SW I2C emulated interface.

1) The Arduino HAL will always send the control byte along with other information after this control byte.
2) The software emulated I2C interface is very slow. I assume, that the 2 clock periods limit will be hit. Nevertheless, I never observed a malfunction here.

If you have to implement your own HAL for the usage with U8g2, my suggestion is to follow the second approach mentioned here:

https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#hardware-i2c-communication

It will ensure, that your OS always transfers a complete sequence of bytes to the I2Cdevice. I mean, a sequence of bytes sent to the SSD1306, will always include the SLA, the command byte and the SSD1306 command or data information.

**Comment by olikraus** [comment] 2018-06-08 12:11
Hmmm I am still not sure whether I understand your problem. 
It is true, that U8g2 has to assemble the full sequence. And actually the construction happens
here:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L421
and here:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L405

BUT: The lower levels should combine this a single sequence of bytes, which should be transfered.

Lets consider this code:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L467

This will transfer a command to the SSD1306 (and other similar controllers with the same protocol):
THe transfer is started, then a 0 byte followed by the actuall command is sent.
This should lead to the following sequence of three bytes
<i2c adr> 0x00 <ssd1306 cmd>
Only the call to "u8x8_byte_EndTransfer(u8x8); " should actually call our OS and transfer these three bytes. In other words: All the three previous bytes need to be stored somewhere and then only with the call to "u8x8_byte_EndTransfer(u8x8); " these three bytes are passed to the HAL I2c transfer procedure.

So, as a conclusion, I do not know how I can support here... What is the bug or the question to U8g2?

By the way: What is your environment? Arduino IDE?

**Comment by desmond-illumadrive** [comment] 2018-06-08 14:42
I am using custom build environment, with custom PCB. My post was referring to a refactoring of the architecture, but I also was not using U8X8_MSG_BYTE_END_TRANSFER and U8X8_MSG_BYTE_START_TRANSFER appropriately. I am using hardware i2c with DMA.

**On another note**
What's the largest number of byte that can be passed the communication callback function before U8X8_MSG_BYTE_END_TRANSFER is called? 
I am finding it's 132 bytes, is this right?

**Comment by desmond-illumadrive** [comment] 2018-06-08 19:50
I am finding sometimes it passes up to 128 bytes into the I2C HAL layer. When I use "u8g2_Setup_ssd1306_128x64_noname_1()" configuration but if I use "u8g2_Setup_ssd1306_128x64_noname_f()" configuration it only send 32 bytes at a time.

When I inspected the call stack I found on line 301 of u8x8_d_ssd1306_128x64_noname.c" it has the comment below. At this point "c" variable is 16, thus the result is 16*8 = 128 byte total.
> u8x8_cad_SendData(u8x8, c*8, ptr); 	/* note: SendData can not handle more than 255 bytes */

**How to reproduce** 

- u8g2_Setup_ssd1306_128x64_noname_1()
- u8g2_InitDisplay()
- u8g2_ClearDisplay(): At this point there a call that will send up to 128bytes.

Is this a bug or am I setting up something incorrectly?

**Comment by olikraus** [comment] 2018-06-09 05:04
Actually `u8x8_cad_SendData()`  may receive up to 255 bytes.
The implementation is here:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L108

So `u8x8_cad_SendData()` will just call your cad callback procedure, which is defined here for i2c:
https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L410

This cad (cad=command/argument/data) procedure will cut down the 128 byte sequence into smaller pieces and handle it over to the u8g2 byte procedure.

**Do you still use the original ssd1306 cad procedure from u8g2 library code (https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_cad.c#L410)?**

Starting from top, the sw levels are this:
u8g2: high level draw procedure, will call display specific code
u8x8_d_ssd1306_128x64_noname.c: display specific code, will call protocol level
u8x8_cad.c: Protocol level, handles D/C flag and others, for I2C is should break down the stream 
u8x8_byte.c: Transmit a byte via the uC hardware system

I also once made a picture about the architecture: 
https://github.com/olikraus/u8g2/blob/master/doc/u8g2_software_architecture.png

> How to reproduce

Can you send me more information about your setup? Can you provide the full code for the setup?

**Comment by olikraus** [comment] 2018-06-09 08:31
I have added the following code, which should halt the system if more than 32 bytes are transmitted:
https://github.com/olikraus/u8g2/blob/731de17c18d680fa254cb45393c469524bc55237/csrc/u8x8_byte.c#L586

I did this under the same setup: g2_Setup_ssd1306_128x64_noname_1()

All works fine. So I actually can not reproduce the problem.

**Comment by olikraus** [comment] 2018-06-17 12:48
no further comments, closing....

**Closed by olikraus** 2018-06-17 12:48 UTC

**Comment by bojanpotocnik** [comment] 2019-08-13 07:31
I had the same problem for the last two days. Debugged and debugged, could not find the problem why my display does ACK on all sent bytes but display nothing. Changed display, still nothing.

Then I went to test other GUI libraries and especially with the help of the Adafruit GFX and ElectronutLabs-bluey driver for SSD1306 I discovered that my OLED's SSD1306 is "strictly datasheet compliant" and expects Control byte in front of every command or sequence of data bytes (datasheet section 8.1.5.1: I2C-bus Write data).

Below is my code for `u8x8_msg_cb byte_cb` which finally works correctly with my 128x64 SSD1306 OLED display (and only this code works).

More information in the comment above `last_ctrl_index`.
Also note that `/* u8g2/u8x8 will never send more than 32 bytes between START_TRANSFER and END_TRANSFER */` from [Porting to new MCU platform - Hardware I2C Communication](https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#hardware-i2c-communication) is not true in that case as it does send up to 137 bytes in my normal usage tests (drawing shapes).
```c
/**
 * @brief Communication callback.
 *
 * @see <a href="https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform#communication-callback-eg-u8x8_byte_hw_i2c">
 * Porting to new MCU platform - The "uC specific" GPIO and Delay callback</a>
 */
static uint8_t u8x8_hw_i2c(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr) {
    static uint8_t buffer[137]; // While testing, up to 137 bytes are sent in one transaction.
    static uint8_t buf_idx = 0;
    /* SSD1306 expects the Control byte in front of every Command (1-3 byte sequence) or sequence of Data bytes.
     *
     * Sources of information, among many more:
     *  https://lastminuteengineers.com/datasheets/SSD1306-128x64-OLED-Driver-Controller-Datasheet.pdf
     *  http://robotcantalk.blogspot.com/2015/03/interfacing-arduino-with-ssd1306-driven.html
     *  https://iotexpert.com/2019/08/07/debugging-ssd1306-display-problems/
     *  https://electronics.stackexchange.com/questions/411116/not-understanding-ssd1306-oled-display-datasheet/411141
     *
     * [ Co | D/C# | 0 | 0 | 0 | 0 | 0 | 0 ]
     * Co is a continuation bit. If set to 1, the controller expects another control byte in this I2C write cycle.
     *   If set to 0, the controller will not expect to receive another control byte in this I2C write cycle.
     *
     * 0x00 (Co = 0, D/C = 0): Next byte(s) are command (non-graphics) data, after which I2C stop condition is expected.
     * 0x80 (Co = 1, D/C = 0): Next byte(s) are command (non-graphics) data, after which another control byte is expected.
     * 0x40 (Co = 0, D/C = 1): Next byte(s) are graphs data, after which I2C stop condition is expected.
     * 0xC0 (Co = 1, D/C = 1): Multiple data or illegal combination?
     *
     * However, it is important that the last Control byte does not have Co bit set as the controller does not
     * reset internal command processor on end of the transfer. If the Co bit of the last command is set, the
     * command processor would then recognize the next received data byte as a Control byte.
     */
    static int16_t last_ctrl_index = -1;

    switch (msg) {
        case U8X8_MSG_BYTE_SEND: {
            uint8_t * data = (uint8_t *) arg_ptr;
            while ((arg_int--) > 0) {
                if (buf_idx >= sizeof(buffer)) {
                    assert(false, "Buffer overrun");
                }
                buffer[buf_idx++] = *(data++);
            }
            break;
        }
        case U8X8_MSG_BYTE_INIT:
            // I2C is already initialized in board.c:board_init_main_peripherals()
            break;
        case U8X8_MSG_BYTE_SET_DC:
            if (buf_idx >= sizeof(buffer)) {
                assert(false, "Buffer overrun");
            }
            // Expect more control bytes by default. If this is the last Control byte,
            // it will be handled in the U8X8_MSG_BYTE_END_TRANSFER case.
            // 0x80 (Co = 1, D/C = 0): Next byte(s) are command (non-graphics) data, after which another control byte is expected.
            // 0x40 (Co = 0, D/C = 1): Next byte(s) are graphs data, after which I2C stop condition is expected.
            last_ctrl_index = buf_idx;
            buffer[buf_idx++] = arg_int ? 0x40 : 0x80;
            break;
        case U8X8_MSG_BYTE_START_TRANSFER:
            buf_idx = 0;
            last_ctrl_index = -1;
            break;
        case U8X8_MSG_BYTE_END_TRANSFER: {
            // Clear the Co bit of the last Control byte.
            if (last_ctrl_index >= 0) {
                buffer[last_ctrl_index] &= ~0x80u;
            }
            uint8_t err = twi_tx(/* 7-bit address = */ u8x8_GetI2CAddress(u8x8) >> 1u, /* p_data = */ buffer, /* len = */, buf_idx);
            if (err != 0) {
                // log error
                return 0;
            }
            break;
        }
        default:
            assert(false, "Unhandled HW I2C message");
            return 0; // The message was not handled successfully
    }
    return 1;
}```
