### ISSUE TITLE
If you use U8G2 ssd1306_128X64 screen, how can you solve this problem

### ISSUE THREAD

**Issue by shisanwanqian** [olikraus/u8g2#1830] opened 2022-04-05 06:39 UTC
If you use U8G2 ssd1306_128X64 screen, how can you solve this problem ,The screen is clear and incomplete ,I used a 1.3-inch 128x64 scree
![79f573a51fb58e1077eec49af1833ba](https://user-images.githubusercontent.com/74062468/161693997-6d4ddeed-d607-49a4-804a-273eecd81f65.jpg)
n

**Comment by olikraus** [comment] 2022-04-05 10:25
Use the correct constructor!
This is not a ssd1306 OLED in your hand.

**Comment by grantbreaksthings** [comment] 2022-04-06 06:00
This is also a duplicate of #1829

**Comment by olikraus** [comment] 2022-04-10 14:02
> This is not a ssd1306 OLED in your hand.

Instead I assume it is a SH1106

**Closed by olikraus** 2022-04-10 14:02 UTC
